[build]
  base    = ""          # เว้นว่างถ้า package.json อยู่ root
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"